/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthentificationRequest } from './models/authentification-request';
export type { AuthentificationResponse } from './models/authentification-response';
export type { RegistrationRequest } from './models/registration-request';
